import { LightSource, LightType, SubjectBounds } from '../types';
import { calculateTargetAngle } from '../lightingModel';

export interface StudioPreset {
  id: string;
  name: string;
  description: string;
  category: string;
  colorBadge: string;
  createLights: (subject?: SubjectBounds) => LightSource[];
}

export const STUDIO_LIGHTING_PRESETS: StudioPreset[] = [
  {
    id: 'three-point',
    name: 'Three-Point Studio',
    description: 'Classic professional 3-point setup (Key, Fill, Rim backlight)',
    category: 'Studio',
    colorBadge: 'from-amber-500 to-indigo-500',
    createLights: (subject) => {
      const sx = subject?.x ?? 50;
      const sy = subject?.y ?? 50;
      return [
        {
          id: crypto.randomUUID(),
          x: Math.max(10, sx - 22),
          y: Math.max(10, sy - 20),
          targetX: sx,
          targetY: sy,
          useTarget: true,
          type: LightType.Spot,
          color: 'Warm Gold (#ff9d42)',
          exposure: 75,
          intensity: 85,
          depthOfField: 20,
          direction: 0,
          rotation: calculateTargetAngle(Math.max(10, sx - 22), Math.max(10, sy - 20), sx, sy),
          size: 110,
          shadowIntensity: 45,
          opacity: 100,
          placement: 'foreground',
          zDepth: 20,
          coneAngle: 45,
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: Math.min(90, sx + 25),
          y: Math.max(10, sy - 12),
          targetX: sx,
          targetY: sy,
          useTarget: true,
          type: LightType.Area,
          color: 'Cool Cyan (#42a5ff)',
          exposure: 45,
          intensity: 50,
          depthOfField: 40,
          direction: 0,
          rotation: calculateTargetAngle(Math.min(90, sx + 25), Math.max(10, sy - 12), sx, sy),
          size: 140,
          shadowIntensity: 20,
          opacity: 80,
          placement: 'foreground',
          zDepth: 10,
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: sx,
          y: Math.max(8, sy - 28),
          type: LightType.Pinpoint,
          color: 'Pure White (#ffffff)',
          exposure: 80,
          intensity: 90,
          depthOfField: 15,
          direction: 0,
          rotation: 0,
          size: 90,
          shadowIntensity: 30,
          opacity: 100,
          placement: 'background',
          rimLightIntensity: 85,
          zDepth: -60,
          enabled: true,
        },
      ];
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour Sunset',
    description: 'Warm low-angle sun rays with cool atmospheric sky fill',
    category: 'Natural',
    colorBadge: 'from-amber-400 to-rose-500',
    createLights: (subject) => {
      const sx = subject?.x ?? 50;
      const sy = subject?.y ?? 50;
      return [
        {
          id: crypto.randomUUID(),
          x: 18,
          y: 22,
          targetX: sx,
          targetY: sy,
          useTarget: true,
          type: LightType.Volumetric,
          color: 'Candlelight Orange (#ff7a00)',
          exposure: 85,
          intensity: 95,
          depthOfField: 30,
          direction: 0,
          rotation: calculateTargetAngle(18, 22, sx, sy),
          size: 160,
          shadowIntensity: 65,
          opacity: 100,
          placement: 'foreground',
          coneAngle: 55,
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: 50,
          y: 12,
          type: LightType.Environment,
          color: 'Cool Cyan (#42a5ff)',
          exposure: 40,
          intensity: 35,
          depthOfField: 50,
          direction: 0,
          rotation: 0,
          size: 200,
          shadowIntensity: 10,
          opacity: 60,
          placement: 'foreground',
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: sx,
          y: Math.max(10, sy - 24),
          type: LightType.Point,
          color: 'Warm Gold (#ff9d42)',
          exposure: 80,
          intensity: 85,
          depthOfField: 20,
          direction: 0,
          rotation: 0,
          size: 100,
          shadowIntensity: 30,
          opacity: 90,
          placement: 'background',
          rimLightIntensity: 90,
          zDepth: -50,
          enabled: true,
        },
      ];
    },
  },
  {
    id: 'cyberpunk',
    name: 'Neon Cyberpunk',
    description: 'High-contrast dual-tone neon key lights with vibrant rim halo',
    category: 'Stylized',
    colorBadge: 'from-rose-500 via-violet-500 to-cyan-400',
    createLights: (subject) => {
      const sx = subject?.x ?? 50;
      const sy = subject?.y ?? 50;
      return [
        {
          id: crypto.randomUUID(),
          x: Math.max(10, sx - 25),
          y: sy,
          targetX: sx,
          targetY: sy,
          useTarget: true,
          type: LightType.Spot,
          color: 'Cyber Red (#ff4242)',
          exposure: 80,
          intensity: 90,
          depthOfField: 15,
          direction: 0,
          rotation: calculateTargetAngle(Math.max(10, sx - 25), sy, sx, sy),
          size: 120,
          shadowIntensity: 70,
          opacity: 100,
          placement: 'foreground',
          coneAngle: 40,
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: Math.min(90, sx + 25),
          y: sy,
          targetX: sx,
          targetY: sy,
          useTarget: true,
          type: LightType.Spot,
          color: 'Neon Violet (#e042ff)',
          exposure: 80,
          intensity: 85,
          depthOfField: 15,
          direction: 0,
          rotation: calculateTargetAngle(Math.min(90, sx + 25), sy, sx, sy),
          size: 120,
          shadowIntensity: 65,
          opacity: 100,
          placement: 'foreground',
          coneAngle: 40,
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: sx,
          y: Math.max(8, sy - 28),
          type: LightType.Point,
          color: 'Aurora Green (#52ff42)',
          exposure: 85,
          intensity: 95,
          depthOfField: 10,
          direction: 0,
          rotation: 0,
          size: 100,
          shadowIntensity: 40,
          opacity: 100,
          placement: 'background',
          rimLightIntensity: 95,
          zDepth: -70,
          enabled: true,
        },
      ];
    },
  },
  {
    id: 'rembrandt',
    name: 'Rembrandt Portrait',
    description: 'Moody classic key light with dramatic cheek shadow & soft fill',
    category: 'Portrait',
    colorBadge: 'from-amber-600 to-stone-800',
    createLights: (subject) => {
      const sx = subject?.x ?? 50;
      const sy = subject?.y ?? 50;
      return [
        {
          id: crypto.randomUUID(),
          x: Math.max(12, sx - 20),
          y: Math.max(12, sy - 22),
          targetX: sx,
          targetY: sy,
          useTarget: true,
          type: LightType.Pinpoint,
          color: 'Warm Gold (#ff9d42)',
          exposure: 85,
          intensity: 90,
          depthOfField: 15,
          direction: 0,
          rotation: calculateTargetAngle(Math.max(12, sx - 20), Math.max(12, sy - 22), sx, sy),
          size: 100,
          shadowIntensity: 85,
          opacity: 100,
          placement: 'foreground',
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: Math.min(88, sx + 22),
          y: Math.min(88, sy + 10),
          type: LightType.Area,
          color: 'Pure White (#ffffff)',
          exposure: 35,
          intensity: 30,
          depthOfField: 45,
          direction: 0,
          rotation: 0,
          size: 150,
          shadowIntensity: 10,
          opacity: 60,
          placement: 'foreground',
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: Math.min(88, sx + 20),
          y: Math.max(10, sy - 30),
          type: LightType.Point,
          color: 'Cool Cyan (#42a5ff)',
          exposure: 50,
          intensity: 45,
          depthOfField: 30,
          direction: 0,
          rotation: 0,
          size: 90,
          shadowIntensity: 20,
          opacity: 70,
          placement: 'background',
          zDepth: -80,
          enabled: true,
        },
      ];
    },
  },
  {
    id: 'film-noir',
    name: 'Film Noir',
    description: 'High-contrast monochrome key spotlight with razor-sharp rim',
    category: 'Dramatic',
    colorBadge: 'from-slate-300 to-black',
    createLights: (subject) => {
      const sx = subject?.x ?? 50;
      const sy = subject?.y ?? 50;
      return [
        {
          id: crypto.randomUUID(),
          x: Math.max(10, sx - 25),
          y: Math.max(10, sy - 25),
          targetX: sx,
          targetY: sy,
          useTarget: true,
          type: LightType.Spot,
          color: 'Pure White (#ffffff)',
          exposure: 95,
          intensity: 100,
          depthOfField: 10,
          direction: 0,
          rotation: calculateTargetAngle(Math.max(10, sx - 25), Math.max(10, sy - 25), sx, sy),
          size: 110,
          shadowIntensity: 100,
          opacity: 100,
          placement: 'foreground',
          coneAngle: 35,
          enabled: true,
        },
        {
          id: crypto.randomUUID(),
          x: sx,
          y: Math.max(10, sy - 22),
          type: LightType.Pinpoint,
          color: 'Pure White (#ffffff)',
          exposure: 90,
          intensity: 100,
          depthOfField: 5,
          direction: 0,
          rotation: 0,
          size: 80,
          shadowIntensity: 50,
          opacity: 100,
          placement: 'background',
          rimLightIntensity: 100,
          zDepth: -50,
          enabled: true,
        },
      ];
    },
  },
];
